language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo: false

env:
  - DB=mysql db_class='Cake\Database\Driver\Mysql' db_dsn='mysql:host=0.0.0.0;dbname=quick_test' db_database='quick_test' db_login='travis' db_password=''

services:
  - memcached
  - redis-server

matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true
  include:
    - php: 5.4
      env: PHPCS=1
    - php: hhvm-nightly
      env: HHVM=1 DB=mysql db_dsn='mysql://travis@0.0.0.0/quick_test'

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev
  - sh -c "if [ '$PHPCS' != '1' ]; then sudo locale-gen de_DE; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE quick_test;'; fi"
  - sh -c "if [ '$PHPCS' != '1' ]; then sudo apt-get install lighttpd; fi"
  - sh -c "if [ '$HHVM' != '1' ]; then echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p -n --ignore=*/Lib/* --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./plugins; fi"

notifications:
  email: false
